#!/bin/bash -x

set -ue

VERSION=1.32.5

git clone https://github.com/dani-garcia/vaultwarden.git
cd vaultwarden
git checkout $VERSION
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
sed "s/---version---/$VERSION/" <../0001-Create-RPM.patch >patch
git am patch
curl https://sh.rustup.rs -sSf | sh -s -- -y
$HOME/.cargo/bin/cargo install cargo-rpm
$HOME/.cargo/bin/cargo rpm build --verbose
rpmdev-extract target/release/rpmbuild/SRPMS/*.src.rpm
mv bitwarden_rs-*.src/ srpm
